# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo Installing Maven
    cd ./apis/user-java
    mvn clean install
    echo Maven Installed Success
    echo Starting Maven Test 
    nvn test
    echo Maven Test Completed
  displayName: 'Run a maven test'
